// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.
// To change the Firebase project, use the "Change Firebase Project" command.
import { initializeApp, getApps, getApp, type FirebaseOptions } from "firebase/app";
import { getAuth } from "firebase/auth";
import { getFirestore } from "firebase/firestore";


/**
 * The Firebase project configuration.
 *
 * This configuration is used to connect to the Firebase project.
 * It is used by the Firebase SDKs to connect to the correct project.
 */
export const firebaseConfig: FirebaseOptions = {
  apiKey: "AIzaSyBfLPoY7rhAhAX30w2hg0Z4ef5kQSVqnBY",
  authDomain: "remaubakotuo-desa-369569-ba4d1.firebaseapp.com",
  projectId: "remaubakotuo-desa-369569-ba4d1",
  storageBucket: "remaubakotuo-desa-369569-ba4d1.appspot.com",
  messagingSenderId: "580823072706",
  appId: "1:580823072706:web:8c531c9066959c3747205b"
};

const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const auth = getAuth(app);
const db = getFirestore(app);

export { app, auth, db };
