'use client';

export const lightTheme = {
  name: "Light",
  sidebar: "#1F2937",
  "sidebar-foreground": "#F9FAFB",
  "sidebar-border": "#374151",
  "sidebar-ring": "#4B5563",
  "sidebar-accent": "#FBBF24",
  "sidebar-accent-foreground": "#111827",
  main: "#F9FAFB",
  "main-foreground": "#111827",
  "main-border": "#E5E7EB",
  "main-ring": "#9CA3AF",
  "main-accent": "#3B82F6",
  "main-accent-foreground": "#F9FAFB",
  "main-card": "#FFFFFF",
  "main-card-foreground": "#111827",
  "main-popover": "#FFFFFF",
  "main-popover-foreground": "#111827",
  "main-primary": "#3B82F6",
  "main-primary-foreground": "#F9FAFB",
  "main-secondary": "#E5E7EB",
  "main-secondary-foreground": "#111827",
  "main-muted": "#F3F4F6",
  "main-muted-foreground": "#6B7280",
  "main-destructive": "#EF4444",
  "main-destructive-foreground": "#F9FAFB",
};
